apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-mikeringrose-com
spec:
  secretName: k8s-mikeringrose-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.mikeringrose.com
  dnsNames:
    - k8s.mikeringrose.com
    - www.k8.mikeringrose.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.mikeringrose.com
          - www.k8s.mikeringrose.com
